// ═══ PERSONALIZA AQUÍ ═══
const CONFIG = {
  // Fecha en que empezaron (formato: AAAA-MM-DDTHH:MM:SS)
  startDate: '2026-04-23T00:00:00',
  // Fecha del 3.er mes (23 abr + 3 meses)
  nextMilestone: '2026-07-23T00:00:00',
  // Archivo de música en carpeta 3ERMES/
  musicFile: 'musica.mp3'
};

const RAZONES = [
  'Por tu sonrisa que ilumina mi día.',
  'Por tus ojos hermosos con los que me miras.',
  'Por hacerme reír sin intentarlo sea con tus caras tan increibles o tu bullyign amigable.',
  'Por tu paciencia conmigo, por que me sabe aguantar cuando mas mal me porto.',
  'Por escucharme de verdad y ser mi confidente y quein guarda mis secretos.',
  'Por tus abrazos que lo arreglan todo y me dan paz.',
  'Por ser tan auténtica y por tu forma tan unica de ser.',
  'Por tu manera de ver la vida y tu locura sin igual✨❤️.',
  'Por los detalles que tienes conmigo ya que eres alguien que no sabe dar poco y de verdad me sorprendes con todo.',
  'Por tu voz cuando me dices cosas bonitas y te esfuerzas al dar esos cumplidos.',
  'Por hacerme sentir en casa solo con tu voz.',
  'Por tu forma de cuidarme aunque a mi me valga jsjsj.',
  'Por los mensajes que me alegran el día desde ese buenos dias hasta ese "yo no te quiero" jsjsj.',
  'Por tu inteligencia y tus ideas tan repentinas pero increibles.',
  'Por acompañarme en lo bueno y en lo difícil y en cada problema que pasa.',
  'Por tu sentido del humor tan distinto y unico que es maravilloso.',
  'Por la confianza que me das en esta relacion.',
  'Por ser mi unica persona favorita.',
  'Por las aventuras que vivimos juntos desde que inicio esta relacion tan unica.',
  'Por tu forma de amar sea con detalles o tus abrazos que se que no se te da tanto❤️.',
  'Por respetarme siempre.',
  'Por hacerme mejor persona.',
  'Por tu calma cuando yo estoy agitado.',
  'Por tu energía cuando la necesito.',
  'Por cocinar juntos (o intentarlo) lo mejor del mundo.',
  'Por las canciones que compartimos la de permiteme JSJSJs.',
  'Por tus besos tan suaves y tiernos❤️.',
  'Por tu forma de decir te quiero porque es como de niña chiquita❤️.',
  'Por los silencios cómodos a tu lado que se hacen risas.',
  'Por apoyar mis sueños y seguir mis locuras.',
  'Por dejarme ser yo mismo y darme aleitno cuando no se si seguir.',
  'Por tus besos tan apasionados que hacen que tenga que acomodarme JAJA.',
  'Por recordar cosas pequeñas de mí como lo son mis gustos peculiares.',
  'Por tu honestidad.',
  'Por hacerme sentir especial cuando estoy contigo .',
  'Por las fotos que guardamos y me dejes tomarte fotos JSJS.',
  'Por tu calidez al abrazarte y tenerte de la mano.',
  'Por los planes que hacemos en 5 minutos y terminamos al otro lado de saltillo .',
  'Por tu valentía para ser tan decidida y firme.',
  'Por perdonarme cuando me equivoco y seguir conmigo hasta el dia de hoy❤️.',
  'Por tu ternura de que te da pena decir cumplidos la vdd lo mejor.',
  'Por la química que hay entre nosotros que digo wow:0.',
  'Por hacerme sentir feliz cuando estoy triste o desanimado.',
  'Por las noches de conversación largas o nos quedamos dormidos en llmda .',
  'Por tu forma de vestir que hace que te veas magnifica 🥰.',
  'Por elegirme cada día desde que te despiertas.',
  'Por ser mi mejor amiga y mi amor que solo pienso en que seas tu.',
  'Por tres meses increíbles.',
  'Por todo lo que falta por vivir.',
  'Porque contigo todo tiene sentido por muy loco que suene.',
  'Por tu risa contagiosa que me encanta.',
  'Por la complicidad en cada mirada y locura juntos.',
  'Por tu elegancia.',
  'Por los abrazos que detienen el tiempo.',
  'Por tu apoyo incondicional.',
  'Por tu manera de incluirme a tu vida.',
  'Por los pequeños detalles diarios.',
  'Por inspirarme a ser mejor cada día.',
  'Por tu ternura infinita.',
  'Por la paz que me transmites.',
  'Por tu valentía ante los retos.',
  'Por nuestras conversaciones nocturnas.',
  'Por hacerme sonreír incluso en los días difíciles.',
  'Por ser mi niña preciosa.',
  'Por tu seriedad cuando no traes animos jsjsj .',
  'Por las cosas que te gustan y amo que me cuentes de como te gustan las cosas .',
  'Por tus audios que me encantan🥰.',
  'Por la forma en que te importo con cada comentario accion que haces:3',
  'Por tus besos que lo curan todo.',
  'Por aceptar mis virtudes y defectos.',
  'Por ser mi refugio seguro cunado siento que no hay nadie.',
  'Por cada aventura vivida a tu lado.',
  'Por los planes que construimos juntos.',
  'Por tu risa cuando te cuento un chiste malo y tu JAJAJA',
  'Por cómo me extrañas cuando no nos vemos en dias.',
  'Por cada dia que comes payaso.',
  'Por tu autenticidad y cruda realidad que tienes a veces JSJSJ.',
  'Por creer en mí incluso cuando yo dudo.',
  'Por tu manera de divertirte junto a mi.',
  'Por ser la persona que me ha hecho vivir cosas nuevas',
  'Por ser mi todo.',
  'Por la magia de coincidir en esta vida.',
  'Por cada instante que aparezco y te sale una sonrisa .',
  'Por tu generosidad y gran corazón que tienes conmigo.',
  'Por la promesa de un futuro juntos.',
  'Por no rendirte facil conmigo.',
  'Por ser esa luz especial en mis días.',
  'Porque simplemente eres tú.',
  'Porque eres y siempre serás el amor de mi vida.',
  'Por tu manera de entenderme sin palabras.',
  'Por tu mirada que me da miedo pero a la vez una calma.',
  'Por tu cariño incondicional poco pero que lo das con mucho esfuerzo.',
  'Por los pequeños momentos que se vuelven gigantes.',
  'Por tus abrazos sinceros que se que te cuestan pero te acostumbraras.',
  'Por tu dulce sonrisa por las mañanas en los videos que me mandas aveces.',
  'Por cada video en los que te vez hermosae.',
  'Porque cada vez que estoy contigo siento que puedo descansar.',
  'Por tu voz, que es mi sonido favorito.',
  'Por ser mi compañera de vida y mi amor eterno todo el tiempo que asi lo queramos✨❤️.',
  'Por tus ganas de pelear que no se comparan con nada❤️.'
];
